### ISSUE TITLE
NativeSubscribe unhandled error and suspected memory leak

### ISSUE THREAD

**Issue by chinaxry** [emeraldpay/dshackle#133]
When I use gRPC NativeSubscribe, it has a very high possibility to throw an exception saying "The mapper returned a null value" after receiving some messages.
Also it seems that there is memory leak, as memory usage goes from 500MB to 5GB in 8 hours.

Below is the related log:
> 2021-04-12 09:56:09.820 | WARN  |          ProduceLogs | No old message to produce removal messages for tx c63c87ae2b3652a517b56c4ab1980de347a6b77a3a3b3b01b5679cf6ae685b79 at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.822 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 6949e37511d234a383b10657d911c853e63b17b16b8a8660e59a40d9b0a74810 at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.822 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 439a04e3534868ba2cd2db7b947533e6babe1cc50a8c4597425bef2e75e00874 at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.823 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 16ff748d6b710a92dd4007056652866028ae73bf986d0945a0238126c5a67555 at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.824 | WARN  |          ProduceLogs | No old message to produce removal messages for tx ab3848a17d9804ec2b6b409ec29188effe8bee98f0de208964f06612978c43e1 at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.830 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 1450d655fa0a0e06c44fb48ba40b65d9cff6d41409d770a52bcda378a240d04d at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.845 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 37dc07252b1149d38cf1f7360d7f97bb6d5496ee9df77dd6679dfd123fac50fe at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.847 | WARN  |          ProduceLogs | No old message to produce removal messages for tx fd79b1c8dc49d95e4eb9c4054bdffc58aebddbc9b1e3a39ce659861522ce0a92 at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.848 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 4b5930fc7f3c6444a8a6579fbe4a0f3d470b3bdb6e743d16b3896a94f1c736ce at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.848 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 23ff9d07d0025f94d17c3b5ec2ea53d007464c33f2118258932cdc5c581e3bed at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.854 | WARN  |          ProduceLogs | No old message to produce removal messages for tx 05b23068ae3347b043322a59fce558f98728567524a5de059e7f58b4b5e0298a at block 68918fcfdd09dc59983bf7d7cc5fde966e48b1a3e6495f09f6c2c4338a0a0fb7
> 2021-04-12 09:56:09.895 | WARN  |      NativeSubscribe | Unhandled error
> java.lang.NullPointerException: The mapper returned a null value.
>         at java.util.Objects.requireNonNull(Objects.java:247) ~[?:?]
>         at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:213) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:229) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142) [reactor-core-3.4.10.jar:3.4.10]
>         at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400) [reactor-netty-core-1.0.11.jar:1.0.11]
>         at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419) [reactor-netty-core-1.0.11.jar:1.0.11]
>         at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473) [reactor-netty-core-1.0.11.jar:1.0.11]
>         at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684) [reactor-netty-http-1.0.11.jar:1.0.11]
>         at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) [reactor-netty-core-1.0.11.jar:1.0.11]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372) [netty-handler-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246) [netty-handler-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286) [netty-handler-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.70.Final.jar:4.1.70.Final]
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.70.Final.jar:4.1.70.Final]
>         at java.lang.Thread.run(Thread.java:830) [?:?]
> 2021-04-12 09:56:09.965 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.965 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.965 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.965 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.971 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.971 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.971 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.972 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.975 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.975 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.975 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.976 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.980 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.981 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.982 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.982 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.982 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.986 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.986 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.986 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.989 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.989 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.989 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.989 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.989 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.990 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.991 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.991 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.992 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.992 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.992 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.992 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.992 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:09.992 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.052 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.052 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.052 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.214 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.214 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.216 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.217 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.217 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.219 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.220 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.220 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.220 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.220 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.230 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.230 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.230 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.230 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.230 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.239 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.239 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.239 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.239 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.239 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.240 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.246 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.246 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.246 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.246 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.246 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.246 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.249 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.249 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.249 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.249 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.250 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.250 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.250 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.250 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.250 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.251 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.252 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.252 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.252 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.252 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER
> 2021-04-12 09:56:10.252 | WARN  | WsFactory$EthereumWs | Failed to proceed with a RPC message: FAIL_ZERO_SUBSCRIBER

**Comment by splix** [comment]
Thank you for the bug report, I'll take a look

**Comment by splix** [comment]
I'm not quite sure I've fixed the bug, but could you try to run with latest dev build to see if anything improved? Thank you

You can get the binary at https://artifacts.emerald.cash/builds/dshackle/2021-12-23/20211224-0751-8526c2a/dshackle-0.12.0-SNAPSHOT.zip
