### ISSUE TITLE
Fails to parse JSON RPC without params

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#19]
JSON RPC spec says:
> **params** [...] This member MAY be omitted.

But it fails with:
```
2020-30-06 03:25:11.752 | ERROR | HttpServerOperations | [id: 0x7d33d59c, L:/172.18.0.3:8080 - R:/172.18.0.1:50322] Error finishing response. Closing connection
io.infinitape.etherjar.rpc.RpcException: RPC Error -32700: null cannot be cast to non-null type kotlin.collections.List<*>
at io.emeraldpay.dshackle.proxy.ReadRpcJson.apply(ReadRpcJson.kt:143) ~[classes/:?]
at io.emeraldpay.dshackle.proxy.ReadRpcJson.apply(ReadRpcJson.kt:39) ~[classes/:?]
```

**Comment by splix** [comment]
rel #17
