### ISSUE TITLE
Unexpected end-of-input

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#29]
Got another interesting error. This time, while using 2 Nethermind nodes, and 1 Geth node...

Config:
```
host: 0.0.0.0
port: 2449
tls:
  enabled: true
  server:
   certificate: "/etc/dshackle/dshackle.crt"
   key: "/etc/dshackle/dshackle.key"
  client:
    require: false

cache:
  redis:
    enabled: true
    host: 192.168.10.50
    port: 6379
    db: 0
    password: "redacted"

proxy:
  host: 0.0.0.0
  port: 8545
  tls:
    enabled: true
    server:
      certificate: "/etc/dshackle/dshackle.crt"
      key: "/etc/dshackle/dshackle.key"
    client:
      require: false
  routes:
    - id: eth
      blockchain: ethereum

cluster:
  defaults:
    - chains:
        - ethereum
      options:
        min-peers: 10
  upstreams:
    - id: nethermind01
      chain: ethereum
      labels:
        provider: nethermind
        nodetype: full
      methods:
        enabled:
          - name: admin_nodeInfo
          - name: admin_peers
          - name: trace_block
          - name: trace_rawTransaction
          - name: trace_replayBlockTransactions
          - name: trace_replayTransaction
          - name: trace_transaction
      connection:
        ethereum:
          rpc:
            url: "http://192.168.15.31:8545"
          ws:
            url: "ws://192.168.15.31:8545/ws/json-rpc"
    - id: nethermind02
      chain: ethereum
      labels:
        provider: nethermind
        nodetype: full
      methods:
        enabled:
          - name: admin_nodeInfo
          - name: admin_peers
          - name: trace_block
          - name: trace_rawTransaction
          - name: trace_replayBlockTransactions
          - name: trace_replayTransaction
          - name: trace_transaction
      connection:
        ethereum:
          rpc:
            url: "http://192.168.15.32:8545"
          ws:
            url: "ws://192.168.15.32:8545/ws/json-rpc"
    - id: geth03
      chain: ethereum
      labels:
        provider: geth
        nodetype: full
      methods:
        enabled:
          - name: admin_nodeInfo
          - name: admin_peers
      connection:
        ethereum:
          rpc:
            url: "http://192.168.10.50:8545"
          ws:
            url: "ws://192.168.10.50:8545"
```

Errors:
```
v0.7.2 built from 881c8c66d7 on 2020-07-03T02:53:12 UTC

2020-06-07 23:58:13.954 | INFO  |            StarterKt | Starting StarterKt on a9b0c2779aa8 with PID 1 (/app/classes started by root in /)
2020-06-07 23:58:13.958 | INFO  |            StarterKt | No active profile set, falling back to default profiles: default
2020-06-07 23:58:15.962 | INFO  |               Config | Using config: /etc/dshackle/dshackle.yaml
2020-06-07 23:58:16.097 | INFO  |        CachesFactory | Use Redis cache at: redis://192.168.10.50
2020-06-07 23:58:16.914 | INFO  |        CachesFactory | Connection to Redis established
2020-06-07 23:58:17.098 | INFO  |           GrpcServer | Starting gRPC Server...
2020-06-07 23:58:17.098 | INFO  |           GrpcServer | Listening Native gRPC on 0.0.0.0:2449
2020-06-07 23:58:17.146 | INFO  |             TlsSetup | Using TLS for Native gRPC
2020-06-07 23:58:17.268 | WARN  |             TlsSetup | Trust all clients for Native gRPC
2020-06-07 23:58:17.977 | INFO  |           GrpcServer | GRPC Server started
2020-06-07 23:58:17.993 | INFO  |          ProxyServer | Listening Proxy on 0.0.0.0:8545
2020-06-07 23:58:18.012 | INFO  |             TlsSetup | Using TLS for proxy
2020-06-07 23:58:18.016 | WARN  |             TlsSetup | Trust all clients for proxy
2020-06-07 23:58:18.301 | INFO  |  ConfiguredUpstreams | Using Ethereum upstream, at http://192.168.15.31:8545, ws://192.168.15.31:8545/ws/json-rpc
2020-06-07 23:58:18.305 | INFO  | WsFactory$EthereumWs | Connecting to WebSocket: ws://192.168.15.31:8545/ws/json-rpc
2020-06-07 23:58:18.406 | INFO  |     EthereumUpstream | Configured for Ethereum
2020-06-07 23:58:18.519 | INFO  | entMultistreamHolder | Upstream nethermind01 with chain ETHEREUM has been added
2020-06-07 23:58:18.519 | INFO  |  ConfiguredUpstreams | Using Ethereum upstream, at http://192.168.15.32:8545, ws://192.168.15.32:8545/ws/json-rpc
2020-06-07 23:58:18.520 | INFO  | WsFactory$EthereumWs | Connecting to WebSocket: ws://192.168.15.32:8545/ws/json-rpc
2020-06-07 23:58:18.600 | INFO  |     EthereumUpstream | Configured for Ethereum
2020-06-07 23:58:18.701 | INFO  | entMultistreamHolder | Upstream nethermind02 with chain ETHEREUM has been added
2020-06-07 23:58:18.702 | INFO  |  ConfiguredUpstreams | Using Ethereum upstream, at http://192.168.10.50:8545, ws://192.168.10.50:8545
2020-06-07 23:58:18.703 | INFO  | WsFactory$EthereumWs | Connecting to WebSocket: ws://192.168.10.50:8545
Socket closed with Method eth_subscribe is not supported
Socket closed with Method eth_subscribe is not supported
2020-06-07 23:58:18.878 | INFO  |     EthereumUpstream | Configured for Ethereum
2020-06-07 23:58:18.898 | INFO  | entMultistreamHolder | Upstream geth03 with chain ETHEREUM has been added
2020-06-07 23:58:19.447 | INFO  |            StarterKt | Started StarterKt in 6.0 seconds (JVM running for 7.107)
2020-06-07 23:58:20.447 | INFO  |          Multistream | State of ETH: height=?, status=UNAVAILABLE/3, lag=[0, 9223372036854775807, 9223372036854775807]
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: (String)"{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x86bb7eb8c90ebc5a084f3d8438f0f561","result":{"parentHash":"0x08772ca73c76a47a2df83ea8de1d25fe6dbab6e21727c0fdb3a2e15991d55669","sha3Uncles":"0x824b0642ab3bf875a3a72317e46ab640bd04188321609a38d00dc64c547bd01a","miner":"0x005e288d713a5fb3d7c9cf1b43810a98688c7223","stateRoot":"0x60ef429cff1253cc7b2177852edd1fc672c1b1b683c9c8f14741119bc79458eb","transactionsRoot":"0x46f4623816019a3b7a521a3575ab95856e7b82315599ba39dd974f40647be98"[truncated 524 chars]; line: 1, column: 2049]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:618)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2037)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2024)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:278)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:264)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2384)
        at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1782)
        at io.infinitape.etherjar.rpc.ws.SubscriptionJsonDeserializer.deserialize(SubscriptionJsonDeserializer.java:33)
        at io.infinitape.etherjar.rpc.ws.SubscriptionJsonDeserializer.deserialize(SubscriptionJsonDeserializer.java:29)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
        at io.infinitape.etherjar.rpc.ws.JacksonWsConverter.readSubscription(JacksonWsConverter.java:35)
        at io.infinitape.etherjar.rpc.ws.SocketApiHandler.channelRead0(SocketApiHandler.java:80)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
io.infinitape.etherjar.rpc.RpcResponseException: Invalid response from RPC endpoint
        at io.infinitape.etherjar.rpc.ws.JacksonWsConverter.readSubscription(JacksonWsConverter.java:38)
        at io.infinitape.etherjar.rpc.ws.SocketApiHandler.channelRead0(SocketApiHandler.java:80)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: (String)"{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x86bb7eb8c90ebc5a084f3d8438f0f561","result":{"parentHash":"0x08772ca73c76a47a2df83ea8de1d25fe6dbab6e21727c0fdb3a2e15991d55669","sha3Uncles":"0x824b0642ab3bf875a3a72317e46ab640bd04188321609a38d00dc64c547bd01a","miner":"0x005e288d713a5fb3d7c9cf1b43810a98688c7223","stateRoot":"0x60ef429cff1253cc7b2177852edd1fc672c1b1b683c9c8f14741119bc79458eb","transactionsRoot":"0x46f4623816019a3b7a521a3575ab95856e7b82315599ba39dd974f40647be98"[truncated 524 chars]; line: 1, column: 2049]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:618)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2037)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2024)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:278)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:264)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2384)
        at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1782)
        at io.infinitape.etherjar.rpc.ws.SubscriptionJsonDeserializer.deserialize(SubscriptionJsonDeserializer.java:33)
        at io.infinitape.etherjar.rpc.ws.SubscriptionJsonDeserializer.deserialize(SubscriptionJsonDeserializer.java:29)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
        at io.infinitape.etherjar.rpc.ws.JacksonWsConverter.readSubscription(JacksonWsConverter.java:35)
        ... 34 more
2020-06-07 23:58:35.443 | INFO  |          Multistream | State of ETH: height=?, status=OK/1,SYNCING/2, lag=[0, 9223372036854775807, 9223372036854775807]
2020-06-07 23:58:50.442 | INFO  |          Multistream | State of ETH: height=?, status=OK/1,SYNCING/2, lag=[0, 9223372036854775807, 9223372036854775807]
2020-06-07 23:59:05.442 | INFO  |          Multistream | State of ETH: height=?, status=OK/1,SYNCING/2, lag=[0, 9223372036854775807, 9223372036854775807]
2020-06-07 23:59:19.442 | INFO  |          Multistream | State of ETH: height=10408971, status=OK/3, lag=[0, 0, 0]
```

[dshackle_error.txt](https://github.com/emeraldpay/dshackle/files/4881720/dshackle_error.txt)

**Comment by splix** [comment]
I also noticed similar errors with Geth:
```
 dshackle[18573]: Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: was expecting closing quote for a string value
 dshackle[18573]:  at [Source: (String)"{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0xb860ccf0e97fdf6cd850eca0a7ac46bb","result":{"parentHash":"0xd193af1c47dc26722339eeb599e232753d4e0218dcccd1bd201b12636d6eb169","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0xea674fdde714fd979de3edf0f56aa9716b898ec8","stateRoot":"0xe1009e3a50f5d0f2ea89cfa58ec2714ef4a0ff636bf85d445fb1fcb3a6493327","transactionsRoot":"0xf76bfbba5c06c299ef87ad570c39929a567c2ddd4267d008b9600c827615d58"[truncated 524 chars]; line: 1, column: 2049]
 dshackle[18573]:         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:618)
 dshackle[18573]:         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2037)
 dshackle[18573]:         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2024)
 dshackle[18573]:         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:278)
 dshackle[18573]:         at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:264)
 dshackle[18573]:         at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:255)
 dshackle[18573]:         at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
 dshackle[18573]:         at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
 dshackle[18573]:         at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
 dshackle[18573]:         at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2384)
 dshackle[18573]:         at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1782)
 dshackle[18573]:         at io.infinitape.etherjar.rpc.ws.SubscriptionJsonDeserializer.deserialize(SubscriptionJsonDeserializer.java:33)
 dshackle[18573]:         at io.infinitape.etherjar.rpc.ws.SubscriptionJsonDeserializer.deserialize(SubscriptionJsonDeserializer.java:29)
 dshackle[18573]:         at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
 dshackle[18573]:         at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
 dshackle[18573]:         at io.infinitape.etherjar.rpc.ws.JacksonWsConverter.readSubscription(JacksonWsConverter.java:35)
```

It seems it doesn't affect the work. Though maybe it breaks WebSocket.
